d = [3, 2, 5, 2, 3,5,3]
print("Sebelum Di hapus")
print(d)
d.pop(
)
d.pop()
print("Setelah Di Hapus")
print(d)
d.append(3)
d.append(7)
d.append(9)
print("Setelah Di Tambah")
print(d)
d.sort()
print("Setelah Di Urutkan")
print(d)
d.clear()
print("Setelah Di Bersihkan")
print(d)